version: '3.9'

services:
  postgres_db:
    container_name: db
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=faqmakerUser
      - POSTGRES_PASSWORD=faqmakerPw
      - POSTGRES_DB=faqmakerDb
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
    driver: local
