version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
