/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './node_modules/@tremor/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        serif: ['var(--font-merriweather)'],
        sans: ['var(--font-inter)'],
      },
      boxShadow: {
        sm: '0 0 0 1px'
      },
      colors: {
        teal: {
          1: "var(--teal-1)",
          2: "var(--teal-2)",
          3: "var(--teal-3)",
          4: "var(--teal-4)",
          5: "var(--teal-5)",
          6: "var(--teal-6)",
          7: "var(--teal-7)",
          8: "var(--teal-8)",
          9: "var(--teal-9)",
          10: "var(--teal-10)",
          11: "var(--teal-11)",
          12: "var(--teal-12)",
          surfaceDark: "#13272580",
          surfaceLight: "#f0faf8cc",
        },
        tealA: {
          1: "var(--teal-a1)",
          2: "var(--teal-a2)",
          3: "var(--teal-a3)",
          4: "var(--teal-a4)",
          5: "var(--teal-a5)",
          6: "var(--teal-a6)",
          7: "var(--teal-a7)",
          8: "var(--teal-a8)",
          9: "var(--teal-a9)",
          10: "var(--teal-a10)",
          11: "var(--teal-a11)",
          12: "var(--teal-a12)",
        },
        red: {
          1: "var(--red-1)",
          2: "var(--red-2)",
          3: "var(--red-3)",
          4: "var(--red-4)",
          5: "var(--red-5)",
          6: "var(--red-6)",
          7: "var(--red-7)",
          8: "var(--red-8)",
          9: "var(--red-9)",
          10: "var(--red-10)",
          11: "var(--red-11)",
          12: "var(--red-12)",
          surfaceDark: "#2f151780",
          surfaceLight: "#fff5f5cc",
        },
        redA: {
          1: "var(--red-a1)",
          2: "var(--red-a2)",
          3: "var(--red-a3)",
          4: "var(--red-a4)",
          5: "var(--red-a5)",
          6: "var(--red-a6)",
          7: "var(--red-a7)",
          8: "var(--red-a8)",
          9: "var(--red-a9)",
          10: "var(--red-a10)",
          11: "var(--red-a11)",
          12: "var(--red-a12)",
        },
        gray: {
          1: "var(--gray-1)",
          2: "var(--gray-2)",
          3: "var(--gray-3)",
          4: "var(--gray-4)",
          5: "var(--gray-5)",
          6: "var(--gray-6)",
          7: "var(--gray-7)",
          8: "var(--gray-8)",
          9: "var(--gray-9)",
          10: "var(--gray-10)",
          11: "var(--gray-11)",
          12: "var(--gray-12)",
        },
        grayA: {
          1: "var(--gray-a1)",
          2: "var(--gray-a2)",
          3: "var(--gray-a3)",
          4: "var(--gray-a4)",
          5: "var(--gray-a5)",
          6: "var(--gray-a6)",
          7: "var(--gray-a7)",
          8: "var(--gray-a8)",
          9: "var(--gray-a9)",
          10: "var(--gray-a10)",
          11: "var(--gray-a11)",
          12: "var(--gray-a12)",
        },
      },
      textColor: {
        default: 'var(--color-text)',
        offset: 'var(--color-text-offset)',
        accent: 'var(--color-text-accent)',
        negative: 'var(--color-text-negative)',
        negativeOffset: 'var(--color-text-negative-offset)',
        error: 'var(--color-text-error)',
      },
      backgroundColor: {
        default: 'var(--color-background)',
        ghost: 'var(--color-background-ghost)',
        offset: 'var(--color-background-offset)',
        accent: 'var(--color-background-accent)',
        accentGhost: 'var(--color-background-accent-ghost)',
        negative: 'var(--color-background-negative)',
        negativeGhost: 'var(--color-background-negative-ghost)',
        negativeOffset: 'var(--color-background-negative-offset)',
        disabled: 'var(--color-background-disabled)',
        error: 'var(--color-background-error)',
        errorOffsetDark: 'var(--color-background-error-offset-dark)',
        errorOffsetLight: 'var(--color-background-error-offset-light)',
      },
      borderColor: {
        default: 'var(--color-border)',
        ghost: 'var(--color-border-ghost)',
        accent: 'var(--color-border-accent)',
        negative: 'var(--color-border-negative)',
        negativeGhost: 'var(--color-border-negative-ghost)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
