export const QueryKeys = {
  NODES: 'nodes',
  NODES_COUNT: 'nodes_count',
  NODE: 'node',
  QUESTIONS: 'questions',
  ANSWERS: 'answers',
  ME: 'me,',
  USERS: 'users',
  USERS_COUNT: 'users_count',
  USER: 'user',
  TAGS: 'tags',
  TENANT: 'tenant',
  SEARCH: 'search',
  INTEGRATION: 'integration',
} as const;
